name: flutter_nov
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  badges: ^1.1.0
  path_drawing: ^0.4.0
  font_awesome_flutter: ^8.5.0
  scrollable_bottom_sheet: ^0.2.1
  dots_indicator: ^1.1.0
  cloud_firestore: ^0.12.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sky.png
    - assets/fitness0.png
    - assets/fitness1.png
    - assets/waffle_image.png
    - assets/waffle_image1.png
    - assets/travel_image.png
    - assets/travel_image1.png
    - assets/travel_image2.png
    - assets/scenery.jpg
    - assets/ramen.jpg
    - assets/rolls.jpg
    - assets/sashimi.jfif
    - assets/yakuza.png
    - assets/yakuza2.png
    - assets/fruit_image.png
    - assets/fruit_image2.png
    - assets/fruit_image3.png
    - assets/delivery.gif
    - assets/wallet.png
    - assets/card.png
    - assets/sim_card.png
    - assets/pos.png
    - assets/bill.png
    - assets/pattern.jpg
    - assets/wine.png
    - assets/wine2.png
    - assets/wine3.png
    - assets/wine4.png
    - assets/emirates.png
    - assets/barcode.jpg
    - assets/aladin.jpg
    - assets/avengers.jpg
    - assets/good_boys.jpg
    - assets/the_hustle.jpg
    - assets/joker.jpg
    - assets/joker_background.jpg
    - assets/fitness_image.PNG

  uses-material-design: true
  fonts:
    - family: BeautyMountainsPersonalUse
      fonts:
        - asset: fonts/BeautyMountainsPersonalUse.ttf
    - family: Hanson-Bold
      fonts:
        - asset: fonts/Hanson-Bold.ttf
    - family: San Marino Beach
      fonts:
       - asset: fonts/San Marino Beach.otf

















