name: flutter_nov
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  badges: ^1.1.0
  path_drawing: ^0.4.0
  font_awesome_flutter: ^8.5.0
  scrollable_bottom_sheet: ^0.2.1
  dots_indicator: ^1.1.0
  cloud_firestore: ^0.12.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sky.png
    - assets/fitness0.png
    - assets/fitness1.png
    - assets/waffle_image.png
    - assets/waffle_image1.png
    - assets/travel_image.png
    - assets/travel_image1.png
    - assets/travel_image2.png
    - assets/scenery.jpg
    - assets/ramen.jpg
    - assets/rolls.jpg
    - assets/sashimi.jfif
    - assets/yakuza.png
    - assets/yakuza2.png
    - assets/fruit_image.png
    - assets/fruit_image2.png
    - assets/fruit_image3.png
    - assets/delivery.gif

  uses-material-design: true
  fonts:
    - family: BeautyMountainsPersonalUse
      fonts:
        - asset: fonts/BeautyMountainsPersonalUse.ttf
    - family: Hanson-Bold
      fonts:
        - asset: fonts/Hanson-Bold.ttf